import Head from 'next/head'
import { Container } from '@/components/Container'
import { WaterCupBottle } from '@/components/WaterCupBottle'


export default function Home() {
  return (
    <>
      <Head>
        <title>Drink Water</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <WaterCupBottle/>
        
      </Container>


    </>
  )
}
